### PR TITLE
Fix infinite loop in Nightclub Money Loop

### PR DESCRIPTION
**Pull request by ezeholz**
Hi! Nice script.

I detected that while using safeLoop, once I tried to stop it I wasn't able to.
That's because the state var isn't updating at all.
I fixed it by linking the local var directly into the loop, and removing the state var. Another fix would be updating the state just at the end of the while iteration, but this solution seems cleaner to me.

### CODE REVIEW

**Comment by L7NEG** [comment]
Sounds great sir if you can share me the changes you did I will add your credits in the next v15

**Comment by L7NEG** [comment]
Great sir thx for the fix ❤👍

**Comment by ezeholz** [comment]
Hi! I don't understand, why did you close it?

**Comment by L7NEG** [comment]
oh i saw your fork and i understand that you are right thats why im adding it in v15 with your github account as credits bro <3

**Comment by L7NEG** [comment]
if you have more globals or updated feature you can continue helping me with your W Pull Requests

**Pull request merged**
